### ISSUE TITLE
Not work for OSX EI Captain

### ISSUE THREAD

**Issue by digdig** [d1ffuz0r/pycharm-themes#13]
<img width="643" alt="1" src="https://cloud.githubusercontent.com/assets/5459093/22316942/8bd97698-e3ab-11e6-8034-2cc26c888149.png">
<img width="975" alt="2" src="https://cloud.githubusercontent.com/assets/5459093/22316941/8bd67b8c-e3ab-11e6-8930-b0ce69a99065.png">

**Comment by d1ffuz0r** [comment]
restart PyCharm and it will show up

**Comment by digdig** [comment]
@d1ffuz0r Won't show up even I've restarted the computer.

**Comment by rbcollins123** [comment]
FYI, same issue here.  I'm also on PyCharm 2016.3.2 (Build #PY-163.10154.50)

**Comment by rbcollins123** [comment]
@digdig apparently these are only editor themes, not entire UI themes...  I see them as selectable in the editor colors & fonts settings: 
![image](https://cloud.githubusercontent.com/assets/11873802/22570260/a20d27ee-e968-11e6-8118-b03997762387.png)

**Comment by digdig** [comment]
@rbcollins123 Then problem is solved, thanks!
