### ISSUE TITLE
Gutter and line number colors

### ISSUE THREAD

**Issue by jameydeorio** [d1ffuz0r/pycharm-themes#7]
Most themes haven't set the right colors for gutter and line numbers (just red on white, which looks pretty awful on dark backgrounds). I think the gutters should match the main background colors, and the line numbers should typically be a little more understated.

**Comment by d1ffuz0r** [comment]
thank you. it'll be fixed for pycharm 5 and other versions compatible with 5th version of style files

**Comment by d1ffuz0r** [comment]
updated all themes
