### ISSUE TITLE
How to make this work in pycharm 4

### ISSUE THREAD

**Issue by nheeren** [d1ffuz0r/pycharm-themes#9]
Hello I can't seem to make this work. I tried many times and I still have only "Default" and "Dracula" under the Appearance settings. I'm on OS X Yosemite. Is the installation guide still up to date for pycharm 4.5? Any ideas?

**Comment by Ajan** [comment]
I'm facing the same trouble. "~/Library/Preferences/PyCharm40/" has only a folder named 'options', where the colors.scheme.xml file is present.

**Comment by nheeren** [comment]
Hmm. Maybe I misunderstood the purpose of these themes. Apparently I can change the code scheme in `Preferences` > `Editor` > `Colors & Fonts`, but not the UI theme in `Preferences` > `Appearance & Behavior` > `Appearance`. If this is the way these themes are supposed to work, please consider this issue solved.

**Comment by d1ffuz0r** [comment]
yes, these themes should work only for the code. global style is a new feature of PyCharm and not supported
